# Automatisk bygging og lansering av commits med versjonstag.
# Hentet fra https://circleci.com/blog/publishing-npm-packages-using-circleci-2-0/

version: 2

defaults: &defaults
    working_directory: ~/repo
    docker:
        - image: circleci/node

jobs:
    bygg:
        <<: *defaults
        steps:
            - checkout

            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
                      - v1-dependencies-

            - run:
                  name: Installer avhengigheter
                  command: npm install

            - run:
                  name: Bygg pakke
                  command: npm run build

            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package.json" }}

            - persist_to_workspace:
                  root: ~/repo
                  paths: .

    publiser:
        <<: *defaults
        steps:
            - attach_workspace:
                  at: ~/repo
            - run:
                  name: Autentiser hos registry
                  command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
            - run:
                  name: Publiser pakke
                  command: npm publish --access public

workflows:
    version: 2
    bygg_og_publiser:
        jobs:
            - bygg:
                  filters:
                      tags:
                          only: /^v.*/

            - godkjenn-publisering:
                  type: approval
                  requires:
                      - bygg
                  filters:
                      tags:
                          only: /^v.*/

            - publiser:
                  requires:
                      - godkjenn-publisering
                  filters:
                      tags:
                          only: /^v.*/
                      branches:
                          ignore: /.*/
