// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bedriftsmeny-sokefelt': string;
  'bedriftsmeny-sokefelt__felt': string;
  'bedriftsmeny-sokefelt__forstorrelsesglass': string;
  'bedriftsmeny-sokefelt__ikon': string;
  'bedriftsmeny-sokefelt__skjult-aria-live-sokeresultat': string;
  'virksomhetsvelger': string;
}
export const cssExports: CssExports;
export default cssExports;
