name: test, build, publish
on:
- push
- workflow_dispatch

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: install dependencies
        run: npm ci

      - name: build
        run: npm run build

      - if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/robustify_brreg'
        name: publish
        run: |
          if jq --null-input --exit-status \
              --argjson local "$(jq .version package.json)" \
              --argjson published "$(npm view --json @navikt/bedriftsmeny versions)" \
              '$published | map(. == $local) | any'
          then
              echo "Version already published. Nothing to do."
          else
              npm publish --access public
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
